name: build

on: [push, pull_request]

jobs:
  build:
    name: verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
        working-directory: functions
      - run: npm run build
        working-directory: functions
